# Generated by Django 4.2.5 on 2023-09-13 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createddate',
            new_name='creationeddate',
        ),
        migrations.AlterField(
            model_name='post',
            name='publictiondate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 12, 39, 43, 241418, tzinfo=datetime.timezone.utc)),
        ),
    ]
