# Generated by Django 4.2.5 on 2023-09-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_postscomments_postcomment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='text',
            new_name='cmnt_text',
        ),
    ]
