# Generated by Django 4.2.1 on 2023-09-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_text_postcomment_cmnt_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='cmnt_text',
            new_name='cmnt_txt',
        ),
    ]
